import = ["/home/gaffclant/.config/alacritty/catppuccin/catppuccin-mocha.toml"]


[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window]
opacity = 0.8
decorations = "None"

[window.padding]
x = 4
y = 1

[colors.footer_bar]
foreground = "#CDD6F4"
background = "#1E1E2E"
